Fix implicit int conversion between int32_t to uint32_t
We just added static_cast so it has an explict cast for integer
conversion.

system/libziparchive/zip_error.cpp:45:24: error: implicit conversion
loses integer precision: 'int32_t' (aka 'int') to 'const uint32_t' (aka
'const unsigned int') [-Werror,-Wimplicit-int-conversion]
   45 |   const uint32_t idx = -error_code;
      |                  ~~~   ^~~~~~~~~~~
1 error generated.

Bug: 430598176
Test: presubmit
Change-Id: Ie3a516ad648bf768e9125d7c6760db168296956a